package com.myRetail.myRetailDemo.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.myRetail.myRetailDemo.constants.Currency;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "PRICE_DETAILS")
@ApiModel(value = "Price Details of the Product")
public class Price {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PRICE_ID")
    @JsonIgnore
    @ApiModelProperty(value = "Price Id of the Product, autogenerated", example = "12222")
    private Long priceId;

    @Column(name = "PRODUCT_ID")
    @ApiModelProperty(value = "Price Id of the Product, autogenerated", example = "33333")
    //@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Long productId;

    @ApiModelProperty(value = "Maximum Retail Price of the Product", example = "500")
    @Column(name = "MRP")
    private Float maxRetailPrice;

    @ApiModelProperty(value = "Offer Price of the Product", example = "250")
    @Column(name = "OFFER_PRICE")
    private Float offerPrice;

    @ApiModelProperty(value = "Currency of the Price. Can take values RUPEES,DOLLARS,POUNDS,EUROS", example = "500")
    @Column(name = "CURRENCY")
    private Currency currency;

    public Price() {

    }

    public Price(Long productId, Float maxRetailPrice, Float offerPrice, Currency currency) {
        this.productId = productId;
        this.maxRetailPrice = maxRetailPrice;
        this.offerPrice = offerPrice;
        this.currency = currency;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public Long getPriceId() {
        return priceId;
    }

    public void setPriceId(Long priceId) {
        this.priceId = priceId;
    }

    public Float getMaxRetailPrice() {
        return maxRetailPrice;
    }

    public void setMaxRetailPrice(Float maxRetailPrice) {
        this.maxRetailPrice = maxRetailPrice;
    }

    public Float getOfferPrice() {
        return offerPrice;
    }

    public void setOfferPrice(Float offerPrice) {
        this.offerPrice = offerPrice;
    }

    public Currency getCurrency() {
        return currency;
    }

    public void setCurrency(Currency currency) {
        this.currency = currency;
    }


}
