package com.myRetail.myRetailDemo.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "PRODUCT_NAME")
@ApiModel(value = "MyRetail Product Name details")
public class ProductName {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PRODUCT_NAME_ID")
    @ApiModelProperty(value = "Product Name ID, Autogenerated for simplicity", example = "111")
    @JsonIgnore
    private Long productNameId;

    @Column(name = "PRODUCT_ID")
    @ApiModelProperty(value = "Product ID, Autogenerated for simplicity", example = "12345")
    //@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private Long productId;

    @Column(name = "PRODUCT_NAME")
    @ApiModelProperty(value = "Product Name", example = "Product Name Test")
    private String productName;

    public ProductName() {

    }

    public ProductName(Long productId, String productName) {
        this.productId = productId;
        this.productName = productName;
    }

    public Long getProductNameId() {
        return productNameId;
    }

    public void setProductNameId(Long productNameId) {
        this.productNameId = productNameId;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }
}
