package com.myRetail.myRetailDemo.entity;


import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;

@Entity
@Table(name = "PRODUCT_DETAILS")
@ApiModel(value = "MyRetail Product details")
public class Product {

    @Id
    @Column(name = "PRODUCT_ID")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "Product ID, Autogenerated for simplicity", example = "12345")
    private Long productId;

    @ApiModelProperty(value = "Product Name, Fetched from another API ", example = "Product Name Test")
    @Transient
    private String productName;

    @ApiModelProperty(value = "Price of the Product, Fetched from ProductName API ")
    @Transient
    private Price price;

    public Product() {

    }

    public Product(String productName, Price price) {
        this.productName = productName;
        this.price = price;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Price getPrice() {
        return price;
    }

    public void setPrice(Price price) {
        this.price = price;
    }
}
